import { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    slug: 'ountodun',
    title: 'Ountodun',
    year: '2025',
    categories: ['Visual Identity', 'Shopify Design'],
    credits: [
      { role: 'Designs', person: 'Ayo' },
      { role: 'Illustrations', person: 'Alex' },
    ],
    thumbnail: '/media/images/ountodun-thumbnail.png',
    bannerImage: '/media/images/ountodun-banner.png',
    description: 'A contemporary luxury concept store identity and Shopify e-commerce experience celebrating African craftsmanship and modern elegance.',
    overview: 'Some detailed case studies showing how we go about designing your products, from research, to ideation, design and presentation.',
    client: 'Ountodun Concept Store',
    typography: {
      logoFontName: 'CANOBIS',
      secondaryFontName: 'Wavehaus',
      logoFontUsage: 'Logo and Brand Name Only',
      secondaryFontUsage: 'Taglines, body text (Light & Book weights)',
      imagePath: '/media/images/ountodun-typography.png',
    },
    colorPalette: [
      { hex: '#EC7320', name: 'Terracotta Warm' },
      { hex: '#841400', name: 'Deep Crimson' },
      { hex: '#FDD6B3', name: 'Alabaster Silk' },
    ],
    galleryImages: [
      '/media/images/ountodun-banner.png',
      '/media/images/ountodun-shopping-bag.png',
      '/media/images/ountodun-color-palette.png',
      '/media/images/ountodun-typography.png',
    ],
    review: {
      quote: 'Studio Ayo elevated our concept store into a global luxury benchmark. The brand identity and Shopify experience captured our heritage with unmatched sophistication.',
      author: 'Ountodun Leadership',
      title: 'Founder & Creative Lead',
    },
  },
  {
    slug: 'natural-american-spirit',
    title: 'Natural American Spirit',
    year: '2026',
    categories: ['3D Modeling', '3D Animation'],
    credits: [
      { role: '3D Model', person: 'Mosa' },
      { role: '3D Animation', person: 'Mosa' },
    ],
    thumbnail: '/media/images/natural-american-spirit-thumbnail.png',
    videoUrl: '/media/videos/natural-american-spirit.mkv',
    description: 'Hyper-realistic 3D product modeling, tactile material exploration, and dynamic motion study.',
    overview: 'An exploration into physical material simulation, high-fidelity lighting, and photorealistic spatial rendering for premium product showcases.',
    client: 'Natural American Spirit',
    galleryImages: [
      '/media/images/natural-american-spirit-thumbnail.png',
    ],
    review: {
      quote: 'The 3D craftsmanship and material render quality produced by Mosa and Studio Ayo was beyond immaculate.',
      author: 'Brand Design Director',
      title: 'Product Marketing',
    },
  },
  {
    slug: 'a-century-flame',
    title: 'A Century Flame',
    year: '2024 - 2026',
    categories: ['Visual Identity', 'Web Design', 'Web Development'],
    credits: [
      { role: 'Designs', person: 'Lanre' },
      { role: 'Web Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/images/a-century-flame-thumbnail.png',
    videoUrl: '/media/videos/a-century-flame-website.mp4',
    description: 'An archival streetwear & heritage fashion house web platform with immersive kinetic typography and editorial layouts.',
    overview: 'Designing an editorial digital home for A Century Flame fashion collection, merging high-contrast black & white imagery with fluid kinetic web interactions.',
    client: 'A Century Flame',
    galleryImages: [
      '/media/images/a-century-flame-thumbnail.png',
    ],
    review: {
      quote: 'Studio Ayo built a digital gallery experience that matched the soul of our clothing collection.',
      author: 'Lanre',
      title: 'Creative Director',
    },
  },
  {
    slug: 'hachi',
    title: 'Hachi',
    year: '2026',
    categories: ['Visual Identity', 'Web App Design', 'Web App Development'],
    credits: [
      { role: 'Designs', person: 'Lanre & Ayo' },
      { role: 'Web Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/images/hachi-thumbnail.png',
    description: 'A revolutionary fintech & digital banking mobile web application with custom retro-futuristic identity.',
    overview: 'Crafting the brand design system, UI design language, and high-performance Web App UI for Hachi.',
    client: 'Hachi Technologies',
    galleryImages: [
      '/media/images/hachi-home-screen.png',
      '/media/images/hachi-login-screen.png',
      '/media/images/hachi-sign-in-screen.png',
      '/media/images/hachi-splash-screen.png',
      '/media/images/hachi-splash-screen-2.png',
    ],
    review: {
      quote: 'Hachi went from concept to a stunning high-converting digital banking app interface thanks to Studio Ayo.',
      author: 'Hachi Product Lead',
      title: 'VP of Product',
    },
  },
  {
    slug: 'faem',
    title: 'Faem',
    year: '2026',
    categories: ['Web Design', 'Web Development'],
    credits: [
      { role: 'Web Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/images/faem-thumbnail.png',
    videoUrl: '/media/videos/faem.mp4',
    description: 'Immersive digital universe for FAËM — an underground sound studio and artist collective website.',
    overview: 'Welcome to FAËM\'s Universe. A digital space thoughtfully curated and designed to offer an immersive dark studio experience.',
    client: 'FAËM Records',
    galleryImages: [
      '/media/images/faem-thumbnail.png',
    ],
    review: {
      quote: 'The website instantly set our universe apart from every traditional record label.',
      author: 'FAËM Management',
      title: 'Studio Director',
    },
  },
  {
    slug: 'bookstool',
    title: 'Bookstool',
    year: '2026',
    categories: ['3D Modeling', 'Product Design'],
    credits: [
      { role: '3D Model & Rendering', person: 'Mosa' },
    ],
    thumbnail: '/media/by-mosa/bookstool/bookstool-full.png',
    description: 'A sculptural, functional stool design combining minimalist geometry with literary storage.',
    overview: 'A 3D design and visualization exploration for a modernist book stool, focusing on functional aesthetics and wood material simulation.',
    client: 'Personal Concept',
    galleryImages: [
      '/media/by-mosa/bookstool/bookstool-full.png',
      '/media/by-mosa/bookstool/bookstool-empty.png',
    ],
  },
  {
    slug: 'retro-camera',
    title: 'Retro Camera Study',
    year: '2026',
    categories: ['3D Modeling', '3D Animation', 'Product Visualization'],
    credits: [
      { role: '3D Modeling & Animation', person: 'Mosa' },
    ],
    thumbnail: '/media/by-mosa/camera/camera-blue.png',
    videoUrl: '/media/by-mosa/camera/camera.mp4',
    description: 'Hyper-realistic 3D rendering and motion study of a classic camera design across multiple colorways.',
    overview: 'An in-depth study of mechanical assembly, lens glass refraction, and product animation of a vintage camera. Multiple color variants explore product personalization.',
    client: 'Product Study',
    galleryImages: [
      '/media/by-mosa/camera/camera-blue.png',
      '/media/by-mosa/camera/camera-brown.png',
      '/media/by-mosa/camera/camera-white.png',
    ],
  },
  {
    slug: 'cosmetic-container',
    title: 'Cosmetic Container Animation',
    year: '2026',
    categories: ['3D Animation', 'Product Visualization', 'CGI'],
    credits: [
      { role: '3D Modeling & Animation', person: 'Mosa' },
    ],
    thumbnail: '/media/by-mosa/cosmetic-container-thumbnail.png',
    videoUrl: '/media/by-mosa/cosmetic-container-animation.mp4',
    description: 'Fluid 3D animation highlighting the elegant packaging form, tactile materiality, and premium branding of high-end cosmetics.',
    overview: 'Motion and rendering study for a premium cosmetic container, utilizing smooth camera pans, depth of field, and fluid simulation.',
    client: 'Cosmetic Concept',
    galleryImages: [
      '/media/by-mosa/cosmetic-container-thumbnail.png',
    ],
  },
  {
    slug: 'modern-lampshade',
    title: 'Modern Lampshade',
    year: '2026',
    categories: ['3D Modeling', 'Product Design', 'Industrial Design'],
    credits: [
      { role: '3D Modeling & Rendering', person: 'Mosa' },
    ],
    thumbnail: '/media/by-mosa/lampshade/lampshade.png',
    description: '3D visualization and lighting simulation of a sculptural modernist lampshade.',
    overview: 'Visualizing a modernist lighting fixture in realistic interior settings. Emphasis on emissive textures, light bounces, and physical material replication.',
    client: 'Lighting Design Concept',
    galleryImages: [
      '/media/by-mosa/lampshade/lampshade.png',
      '/media/by-mosa/lampshade/lampshade-in-scene.png',
    ],
  },
  {
    slug: 'vietnam-cities',
    title: 'Vietnam Cities Series',
    year: '2026',
    categories: ['Illustration', 'Digital Art', 'Travel Art'],
    credits: [
      { role: 'Illustrations', person: 'Alex' },
    ],
    thumbnail: '/media/by-alex/hanoi-city-illustration.PNG',
    description: 'A vibrant series of digital illustrations capturing the energy, architecture, and spirit of Hanoi, Da Nang, and Saigon.',
    overview: 'Travel illustration series visualizing major urban landscapes in Vietnam, featuring detailed street scenes, historic landmarks, and signature color stories.',
    client: 'Art Series',
    galleryImages: [
      '/media/by-alex/hanoi-city-illustration.PNG',
      '/media/by-alex/da-nang-city-illustration.PNG',
      '/media/by-alex/saigon-city-illustration.PNG',
    ],
  },
  {
    slug: 'portrait-studies',
    title: 'Portrait Studies',
    year: '2026',
    categories: ['Illustration', 'Digital Art', 'Fine Art'],
    credits: [
      { role: 'Illustrations', person: 'Alex' },
    ],
    thumbnail: '/media/by-alex/portrait-study-illustration.PNG',
    description: 'An expressive series of digital portrait studies exploring form, lighting, color, and character.',
    overview: 'A collection of portrait paintings exploring digital brushwork, stylized skin tones, and expressive character concepts.',
    client: 'Art Study',
    galleryImages: [
      '/media/by-alex/portrait-study-illustration.PNG',
      '/media/by-alex/portrait-study-2-illustration.PNG',
      '/media/by-alex/portrait-study-3-illustration.PNG',
      '/media/by-alex/2-portrait-study-illustration.PNG',
      '/media/by-alex/2-portrait-study-2-illustration.PNG',
      '/media/by-alex/2-portrait-study-3-illustration.PNG',
    ],
  },
  {
    slug: 'selected-illustrations',
    title: 'Selected Illustrations',
    year: '2026',
    categories: ['Illustration', 'Pop Culture', 'Digital Art'],
    credits: [
      { role: 'Illustrations', person: 'Alex' },
    ],
    thumbnail: '/media/by-alex/riri-illustration.png',
    description: 'A curated collection of illustrations bridging anime, pop culture icons, still life, and team portraits.',
    overview: 'A portfolio collection of illustration commissions and self-initiated projects, featuring iconic references, still life explorations, and group drawings.',
    client: 'Various Clients',
    galleryImages: [
      '/media/by-alex/riri-illustration.png',
      '/media/by-alex/tatted-babe-illustration.png',
      '/media/by-alex/luffy-illustration.jpeg',
      '/media/by-alex/luffy-2-illustration.jpg',
      '/media/by-alex/omelette-illustration.PNG',
      '/media/by-alex/form-and-light-illustration.PNG',
      '/media/by-alex/opn-team-at-ncs-illustration.jpg',
    ],
  },
  {
    slug: 'want-magazine',
    title: 'WANT Magazine',
    year: '2025',
    categories: ['Editorial Design', 'Creative Direction', 'Graphic Design'],
    credits: [
      { role: 'Creative Direction & Design', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/want-magazine-cover.png',
    description: 'A high-fashion print and digital magazine concept exploring contemporary streetwear, product design, and cultural narratives.',
    overview: 'WANT Magazine is an editorial design concept featuring custom layouts, typography, and product spreads. The visual design highlights premium street culture and minimalist styling.',
    client: 'WANT Collective',
    galleryImages: [
      '/media/by-ayo/want-magazine-cover.png',
      '/media/by-ayo/want-magazine-exotic.png',
      '/media/by-ayo/want-magazine-jersey.png',
      '/media/by-ayo/want-magazine-jeans.png',
      '/media/by-ayo/want-magazine-loafers.png',
      '/media/by-ayo/want-magazine-ties.png',
      '/media/by-ayo/want-magazine-tracks.png',
      '/media/by-ayo/want-magazine-caps.png',
      '/media/by-ayo/want-magazine-belts.png',
    ],
  },
  {
    slug: 'napoli-pizzeria',
    title: 'Napoli Pizzeria',
    year: '2025',
    categories: ['Brand Identity', 'Packaging Design', 'Graphic Design'],
    credits: [
      { role: 'Brand Design', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/napoli-pizzeria-pizza-box.png',
    description: 'A modern, typography-driven brand identity and packaging design system for an artisanal Italian pizzeria.',
    overview: 'Napoli Pizzeria identity merges classic Italian woodcut aesthetics with clean modernist type. Custom pizza box designs and logos form a cohesive, premium takeout experience.',
    client: 'Napoli Pizzeria',
    galleryImages: [
      '/media/by-ayo/napoli-pizzeria-pizza-box.png',
      '/media/by-ayo/napoli-pizzeria-logo.png',
    ],
  },
  {
    slug: 'opn-wrld-posters',
    title: 'Opn Wrld Poster Series',
    year: '2025 - 2026',
    categories: ['Graphic Design', 'Poster Art', 'Creative Direction'],
    credits: [
      { role: 'Graphic Design', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/opn-wrld-hypedup-hillbillies-poster.png',
    description: 'A dynamic series of posters, album artworks, and typographic experiments exploring pop culture, raw texture, and editorial hierarchies.',
    overview: 'A personal archive of posters, print layouts, and album cover designs including the Opn Wrld series, Sexy 5000, and The Ninja illustrations.',
    client: 'Self-Initiated',
    galleryImages: [
      '/media/by-ayo/opn-wrld-hypedup-hillbillies-poster.png',
      '/media/by-ayo/dejizus-poster.jpg',
      '/media/by-ayo/opn-wrld-crowd-poster.jpg',
      '/media/by-ayo/opn-wrld-live-the-ride-poster.png',
      '/media/by-ayo/opn-wrld-ywe-poster.jpg',
      '/media/by-ayo/unc-mo-poster.jpg',
      '/media/by-ayo/currency-design-experiment.JPG',
      '/media/by-ayo/sexy-5000-album-cover.jpeg',
      '/media/by-ayo/the-ninja-illustration.png',
    ],
  },
  {
    slug: 'eoe-website',
    title: 'EOE Web Experience',
    year: '2026',
    categories: ['Web Design', 'Web Development', 'Interactive Design'],
    credits: [
      { role: 'Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/eoe-website-thumbnail.png',
    videoUrl: '/media/by-ayo/eoe-website.mp4',
    description: 'Immersive kinetic digital platform featuring experimental typography, audio-visual feedback loops, and smooth web layouts.',
    overview: 'An interactive web design and development project showcasing high-performance transitions, customized micro-interactions, and horizontal layouts.',
    client: 'EOE Collective',
    galleryImages: ['/media/by-ayo/eoe-website-thumbnail.png'],
  },
  {
    slug: 'luffyworld-website',
    title: 'Luffyworld Web Experience',
    year: '2026',
    categories: ['Web Design', 'Web Development', 'Concept Art'],
    credits: [
      { role: 'Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/luffyworld-website-thumbnail.png',
    videoUrl: '/media/by-ayo/luffyworld-website.mp4',
    description: 'An immersive, media-rich web experience and portfolio layout themed around anime, character design, and kinetic interaction.',
    overview: 'Web development project focusing on responsive layouts, video asset management, and animated typographic grids.',
    client: 'Luffyworld',
    galleryImages: ['/media/by-ayo/luffyworld-website-thumbnail.png'],
  },
  {
    slug: 'masher-website',
    title: 'Masher Web Platform',
    year: '2026',
    categories: ['Web Design', 'Web Development', 'UI/UX'],
    credits: [
      { role: 'Design & Dev', person: 'Ayo' },
    ],
    thumbnail: '/media/by-ayo/masher-website-thumbnail.png',
    videoUrl: '/media/by-ayo/masher-website.mp4',
    description: 'A dark-mode portfolio landing page and web application interface with responsive layout cards and fluid smooth scroll.',
    overview: 'Designing and developing the main digital home for Masher, emphasizing typography, spacing, and transition speeds.',
    client: 'Masher Studio',
    galleryImages: ['/media/by-ayo/masher-website-thumbnail.png'],
  },
];

